import React, {useEffect, useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {LayoutDashboard, ListTodo, Tags, Plus, Search, LogOut, CheckCircle2, Clock3, AlertCircle, Trash2, ArrowRight, X, Menu, ShieldCheck} from 'lucide-react'
import './styles.css'

const API='/api'
const getStored=k=>localStorage.getItem(k)
const setStored=(k,v)=>localStorage.setItem(k,v)
const clearStored=()=>['stm_access_token','stm_refresh_token','stm_email'].forEach(k=>localStorage.removeItem(k))

function App(){
 const [token,setToken]=useState(getStored('stm_access_token'))
 const [refresh,setRefresh]=useState(getStored('stm_refresh_token'))
 const [email,setEmail]=useState(getStored('stm_email'))
 const [authMode,setAuthMode]=useState('login')
 const [view,setView]=useState('dashboard')
 const [tasks,setTasks]=useState([])
 const [categories,setCategories]=useState(()=>JSON.parse(getStored('stm_categories')||'[]'))
 const [loading,setLoading]=useState(false)
 const [toast,setToast]=useState(null)
 const [modal,setModal]=useState(null)
 const [mobileOpen,setMobileOpen]=useState(false)
 const [filters,setFilters]=useState({q:'',status:'',priority:''})

 const notify=(message,type='success')=>{setToast({message,type});setTimeout(()=>setToast(null),3000)}
 const saveSession=(data,userEmail)=>{const t=data.token||data.accessToken; if(t){setToken(t);setStored('stm_access_token',t)} if(data.refreshToken){setRefresh(data.refreshToken);setStored('stm_refresh_token',data.refreshToken)} if(userEmail){setEmail(userEmail);setStored('stm_email',userEmail)}}
 const logout=async()=>{try{if(token) await api('/auth/logout',{method:'POST'},false)}catch{} finally{setToken(null);setRefresh(null);setEmail(null);clearStored();setTasks([]);setView('dashboard');notify('Signed out.')}}

 async function api(path,options={},retry=true){
   const headers={...(options.headers||{})}; if(token) headers.Authorization=`Bearer ${token}`; if(options.body) headers['Content-Type']='application/json'
   const res=await fetch(API+path,{...options,headers})
   if((res.status===401||res.status===403)&&retry&&refresh){
     const rr=await fetch(API+'/auth/refresh-token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken:refresh})})
     if(rr.ok){const data=await rr.json();saveSession(data);return api(path,options,false)}
     await logout(); throw new Error('Session expired. Please sign in again.')
   }
   if(!res.ok){let msg=`Request failed (${res.status})`;try{const b=await res.json();if(b.message)msg=b.message}catch{};throw new Error(msg)}
   if(res.status===204)return null; const text=await res.text(); return text?JSON.parse(text):null
 }
 const loadTasks=async()=>{setLoading(true);try{setTasks(await api('/tasks')||[])}catch(e){notify(e.message,'error')}finally{setLoading(false)}}
 useEffect(()=>{if(token)loadTasks()},[token])

 const filtered=useMemo(()=>tasks.filter(t=>(!filters.q||t.title?.toLowerCase().includes(filters.q.toLowerCase()))&&(!filters.status||String(t.status).toUpperCase()===filters.status)&&(!filters.priority||String(t.priority).toUpperCase()===filters.priority)),[tasks,filters])
 const stats=useMemo(()=>({total:tasks.length,progress:tasks.filter(t=>String(t.status).toUpperCase()==='IN_PROGRESS').length,done:tasks.filter(t=>String(t.status).toUpperCase()==='COMPLETED').length,upcoming:tasks.filter(t=>t.dueDate&&new Date(t.dueDate)>=new Date(new Date().toDateString())&&String(t.status).toUpperCase()!=='COMPLETED').length}),[tasks])

 if(!token) return <Auth mode={authMode} setMode={setAuthMode} onLogin={d=>{saveSession(d,d.email);}} api={api} saveSession={saveSession} notify={notify}/>
 return <div className="app-shell">
   <aside className={`sidebar ${mobileOpen?'open':''}`}><div className="brand"><div className="brand-mark"><CheckCircle2 size={21}/></div><div><b>SmartTask</b><span>Manager</span></div></div>
    <nav>{[['dashboard','Overview',LayoutDashboard],['tasks','My Tasks',ListTodo],['categories','Categories',Tags]].map(([key,label,Icon])=><button key={key} className={view===key?'nav active':'nav'} onClick={()=>{setView(key);setMobileOpen(false)}}><Icon size={19}/>{label}</button>)}</nav>
    <div className="sidebar-bottom"><div className="security"><ShieldCheck size={17}/><span>JWT secured</span></div><button className="nav logout" onClick={logout}><LogOut size={18}/>Sign out</button></div>
   </aside>
   {mobileOpen&&<div className="overlay" onClick={()=>setMobileOpen(false)}/>} 
   <main className="main"><header><button className="mobile-menu" onClick={()=>setMobileOpen(true)}><Menu/></button><div><p className="eyebrow">WORKSPACE</p><h1>{view==='dashboard'?'Overview':view==='tasks'?'My Tasks':'Categories'}</h1></div><div className="profile"><div className="avatar">{(email||'U')[0].toUpperCase()}</div><div className="profile-text"><b>{email}</b><span>Personal workspace</span></div></div></header>
    {view==='dashboard'&&<Dashboard stats={stats} tasks={tasks} onAdd={()=>setModal('task')} onView={()=>setView('tasks')} loading={loading}/>} 
    {view==='tasks'&&<TasksView tasks={filtered} filters={filters} setFilters={setFilters} onAdd={()=>setModal('task')} onDelete={async id=>{try{await api(`/deleteTask/${id}`,{method:'DELETE'});notify('Task deleted');loadTasks()}catch(e){notify(e.message,'error')}}} onStatus={async(t)=>{const current=String(t.status).toUpperCase();const next=current==='PENDING'?'IN_PROGRESS':current==='IN_PROGRESS'?'COMPLETED':'PENDING';try{await api(`/tasks/${t.id}`,{method:'PUT',body:JSON.stringify({status:next})});notify(`Status changed to ${next.replace('_',' ')}`);loadTasks()}catch(e){notify(e.message,'error')}}}/>}
    {view==='categories'&&<Categories categories={categories} onCreate={async(name,colour)=>{try{await api('/category',{method:'POST',body:JSON.stringify({name,colour})});const next=[...new Set([...categories,name])];setCategories(next);setStored('stm_categories',JSON.stringify(next));notify('Category created')}catch(e){notify(e.message,'error')}}}/>} 
   </main>
   {modal==='task'&&<TaskModal categories={categories} onClose={()=>setModal(null)} onCreate={async data=>{try{await api('/tasks',{method:'POST',body:JSON.stringify(data)});setModal(null);notify('Task created');loadTasks()}catch(e){notify(e.message,'error')}}}/>} 
   {toast&&<div className={`toast ${toast.type}`}>{toast.message}</div>}
 </div>
}

function Auth({mode,setMode,api,saveSession,notify}){const [form,setForm]=useState({name:'',email:'',password:''});const [busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);try{if(mode==='register'){await api('/auth/register',{method:'POST',body:JSON.stringify({fullName:form.name,email:form.email,password:form.password})},false);notify('Account created. Sign in to continue.');setMode('login')}else{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:form.email,password:form.password})},false);saveSession({...d,email:form.email},form.email)}}catch(err){notify(err.message,'error')}finally{setBusy(false)}};return <div className="auth-page"><div className="auth-glow one"/><div className="auth-glow two"/><section className="auth-card"><div className="auth-brand"><div className="brand-mark"><CheckCircle2 size={24}/></div><span>SmartTask</span></div><div className="auth-copy"><p className="eyebrow">YOUR PRODUCTIVITY HUB</p><h1>Turn plans into <em>progress.</em></h1><p>Manage tasks, priorities and deadlines from one focused workspace.</p></div><div className="auth-tabs"><button className={mode==='login'?'selected':''} onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'selected':''} onClick={()=>setMode('register')}>Create account</button></div><form onSubmit={submit}>{mode==='register'&&<Field label="Full name" value={form.name} onChange={v=>setForm({...form,name:v})} placeholder="Your name"/>}<Field label="Email" type="email" value={form.email} onChange={v=>setForm({...form,email:v})} placeholder="you@example.com"/><Field label="Password" type="password" value={form.password} onChange={v=>setForm({...form,password:v})} placeholder="••••••••"/><button className="primary full" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}<ArrowRight size={18}/></button></form><p className="auth-note">Protected by Spring Security + JWT authentication</p></section></div>}
function Field({label,value,onChange,type='text',placeholder}){return <label className="field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} required/></label>}

function Dashboard({stats,tasks,onAdd,onView,loading}){const recent=[...tasks].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5);return <div className="content"><div className="hero"><div><p className="eyebrow">GOOD TO SEE YOU</p><h2>Make today <span>count.</span></h2><p>Keep your priorities clear and your momentum going.</p></div><button className="primary" onClick={onAdd}><Plus size={18}/>New task</button></div><div className="stats">{[['Total tasks',stats.total,ListTodo,'neutral'],['In progress',stats.progress,Clock3,'blue'],['Completed',stats.done,CheckCircle2,'green'],['Upcoming',stats.upcoming,AlertCircle,'orange']].map(([l,n,I,c])=><div className="stat" key={l}><div className={`stat-icon ${c}`}><I size={19}/></div><div><span>{l}</span><strong>{n}</strong></div></div>)}</div><div className="section-head"><div><p className="eyebrow">RECENT ACTIVITY</p><h3>Latest tasks</h3></div><button className="ghost" onClick={onView}>View all <ArrowRight size={16}/></button></div><div className="task-list">{loading?<div className="empty">Loading tasks…</div>:recent.length?recent.map(t=><TaskRow key={t.id} task={t}/>):<div className="empty"><ListTodo size={30}/><b>No tasks yet</b><span>Create your first task and start building momentum.</span><button className="primary" onClick={onAdd}><Plus size={17}/>Create task</button></div>}</div></div>}
function TasksView({tasks,filters,setFilters,onAdd,onDelete,onStatus}){return <div className="content"><div className="toolbar"><div className="search"><Search size={18}/><input value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})} placeholder="Search tasks…"/></div><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All status</option><option value="PENDING">Pending</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></select><select value={filters.priority} onChange={e=>setFilters({...filters,priority:e.target.value})}><option value="">All priority</option><option value="HIGH">High</option><option value="MEDIUM">Medium</option><option value="LOW">Low</option></select><button className="primary" onClick={onAdd}><Plus size={18}/>New task</button></div><div className="task-list">{tasks.length?tasks.map(t=><TaskRow key={t.id} task={t} actions onStatus={()=>onStatus(t)} onDelete={()=>onDelete(t.id)}/>):<div className="empty"><Search size={30}/><b>No matching tasks</b><span>Try changing your filters or create a new task.</span></div>}</div></div>}
function TaskRow({task,actions,onStatus,onDelete}){const status=String(task.status||'').toUpperCase(), priority=String(task.priority||'').toUpperCase();return <article className="task-row"><div className="task-main"><div className={`status-dot ${status.toLowerCase()}`}/><div><h4>{task.title}</h4><p>{task.description||'No description'}</p><div className="meta"><span className={`badge ${status.toLowerCase()}`}>{status.replace('_',' ')}</span><span className={`badge ${priority.toLowerCase()}`}>{priority}</span>{task.category&&<span className="badge category">{task.category}</span>}<span className="date">Due {formatDate(task.dueDate)}</span></div></div></div>{actions&&<div className="row-actions"><button title="Change status" onClick={onStatus}><CheckCircle2 size={17}/></button><button className="danger" title="Delete" onClick={onDelete}><Trash2 size={17}/></button></div>}</article>}
function Categories({categories,onCreate}){const [name,setName]=useState('');const [colour,setColour]=useState('#8b5cf6');return <div className="content"><div className="category-intro"><div><p className="eyebrow">ORGANIZE YOUR WORK</p><h2>Categories</h2><p>Use simple labels to keep related tasks together.</p></div></div><div className="category-grid"><form className="panel category-form" onSubmit={e=>{e.preventDefault();if(name.trim()){onCreate(name.trim(),colour);setName('')}}}><h3>Create category</h3><p>Add a label you can use when creating tasks.</p><Field label="Name" value={name} onChange={setName} placeholder="e.g. Work"/><label className="field"><span>Colour</span><div className="colour-input"><input type="color" value={colour} onChange={e=>setColour(e.target.value)}/><code>{colour}</code></div></label><button className="primary full"><Plus size={18}/>Create category</button></form><div className="panel"><div className="panel-head"><h3>Your categories</h3><span>{categories.length}</span></div>{categories.length?<div className="chips">{categories.map((c,i)=><div className="category-chip" key={c}><i style={{background:['#8b5cf6','#06b6d4','#f59e0b','#10b981','#f43f5e'][i%5]}}/>{c}</div>)}</div>:<div className="empty compact"><Tags size={28}/><span>No categories yet.</span></div>}</div></div></div>}
function TaskModal({categories,onClose,onCreate}){const [form,setForm]=useState({title:'',description:'',status:'PENDING',priority:'MEDIUM',dueDate:new Date(Date.now()+86400000).toISOString().slice(0,10),category:categories[0]||''});const update=(k,v)=>setForm({...form,[k]:v});return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="modal" onSubmit={e=>{e.preventDefault();onCreate(form)}}><div className="modal-head"><div><p className="eyebrow">NEW TASK</p><h3>Create a task</h3></div><button type="button" className="close" onClick={onClose}><X/></button></div><Field label="Title" value={form.title} onChange={v=>update('title',v)} placeholder="What needs to be done?"/><label className="field"><span>Description</span><textarea value={form.description} onChange={e=>update('description',e.target.value)} placeholder="Add a little context…" required/></label><div className="form-grid"><label className="field"><span>Status</span><select value={form.status} onChange={e=>update('status',e.target.value)}><option>PENDING</option><option>IN_PROGRESS</option><option>COMPLETED</option></select></label><label className="field"><span>Priority</span><select value={form.priority} onChange={e=>update('priority',e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label></div><div className="form-grid"><label className="field"><span>Due date</span><input type="date" value={form.dueDate} onChange={e=>update('dueDate',e.target.value)} required/></label><label className="field"><span>Category</span><input list="categories" value={form.category} onChange={e=>update('category',e.target.value)} placeholder="Work" required/><datalist id="categories">{categories.map(c=><option key={c} value={c}/>)}</datalist></label></div><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Cancel</button><button className="primary"><Plus size={18}/>Create task</button></div></form></div>}
function formatDate(v){if(!v)return '—';return new Date(v+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}

createRoot(document.getElementById('root')).render(<App/>)
